name: sure3
favicon: null
layout_spectrum: 0.34958
typography_spectrum: 0.5
title: Online Restaurant Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#818282'
    - '#5aba47'
    - '#a4a5a5'
    - '#dfe3e3'
    - '#8dcf80'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
