name: sure3
favicon: null
layout_spectrum: 0.04188108118250966
typography_spectrum: 0.20199142023921013
title: Online Restaurant Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#818282'
    - '#5aba47'
    - '#a4a5a5'
    - '#dfe3e3'
    - '#8dcf80'
  brandStrength: 0.8125
  lightness: 0.44037283398211
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
