name: sure3
favicon: null
layout_spectrum: 0.04188108118250966
typography_spectrum: 0.20199142023921013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8030231564771384
  lightness: 0.44037283398211
  saturation: 0.08028865279629827
  rhythmicContrast: 0.015090641798451543
purpose: []
